#! /bin/sh

echo ">>>run app"
echo "*******mount********"
/bin/mount -a

mkdir /dev/part
ln -s /dev/mmcblk1p1 /dev/part/bld
ln -s /dev/mmcblk1p2 /dev/part/cfg
ln -s /dev/mmcblk1p3 /dev/part/sys
ln -s /dev/mmcblk1p4 /dev/part/app
ln -s /dev/mmcblk1p5 /dev/part/ext
ln -s /dev/mmcblk1p6 /dev/part/store
mkdir /nfs
ifconfig eth0 down && ifconfig eth0 hw ether 00:1A:2B:3C:4D:5E && \
ifconfig eth0 192.168.1.30 netmask 255.255.255.0 up &&  \
route add default gw 192.168.1.1
mount -t nfs -o nolock,nfsvers=3 192.168.1.69:/home/he/Desktop/linux/alpha/nfs /nfs/

dropbear -R -I 1800

