#! /bin/sh

echo -e "\n******* run app ******* \n"
mount -a

mkdir /nfs
# ifconfig eth0 down && \
ifconfig eth0 hw ether 00:1A:2B:3C:4D:5E && \
ifconfig eth0 192.168.1.30 netmask 255.255.255.0 &&  \
route add default gw 192.168.1.1 && \
# ifconfig eth0 up
mount -t nfs -o nolock,nfsvers=3 192.168.1.69:/home/he/Desktop/linux/alpha/nfs /nfs/
dropbear -R -I 1800





